spring.application.name=GenoPharma
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=popo
spring.datasource.driver-class-name=org.postgresql.Driver


spring.batch.jdbc.initialize-schema=always

batch.chunk.size=1

sftp.host=localhost
sftp.port=22
sftp.user=user
sftp.password=password


vcf.inputDirectory=/home/corv/projects/GenoPharma/in