CREATE TABLE IF NOT EXISTS  sample (
                               sample_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               content_hash varchar(64),
                               status smallint NOT NULL,
                               error_code integer,
                               file_name varchar(255) NOT NULL,
                               absolute_path varchar(1024) NOT NULL,
                               size_bytes bigint NOT NULL,
                               last_modified_time TIMESTAMP,
                               vcf_version varchar(20),
                               reference_genome varchar(50),
                               created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sample_hash ON sample (content_hash);